EXPERIMENT: "resnext"

SYSTEM:
  NUM_WORKERS: 8

DIRS:
  # DATA: "data"
  DATA: "/home/huyphan1/quang/occlusion/faces"
  LOGS: "logs"
  WEIGHTS: "weights"

MODEL:
  NAME: "GEMPoolCNN"

  NUM_CLASSES: 6

  BACKBONE:
    ARCH: "resnext50_32x4d"

TRAIN:
  BATCH_SIZE: 128
  EPOCHS: 20

OPT:
  OPTIMIZER: "adamw"
  WEIGHT_DECAY: 1e-4
  BASE_LR: 1e-3
  BACKBONE_LR: 1e-3
  WARMUP_EPOCHS: 2

DATA:
  HEIGHT: 224
  WIDTH: 224
  CUTOUT: True

  INTERP: 2